@extends('layouts.white')
@section('content')

<!--
<iframe width=60% height="800" src="https://datastudio.google.com/embed/reporting/11yc6cwMjqK80QoqwryHdc2cf2Z_KvbgX/page/JgD" frameborder="0" style="border:0" allowfullscreen></iframe>
-->
<div class='tableauPlaceholder' id='viz1515575095288' style='position: relative'><noscript><a href='#'><img alt='圖書館資料 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;201607_2&#47;sheet6&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='201607_2&#47;sheet6' /><param name='tabs' value='no' /><param name='toolbar' value='no' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;201607_2&#47;sheet6&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1515575095288');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1000px';vizElement.style.height='827px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

@endsection
